-- TABLA: grupos_articulos
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (1, 'REPUESTOS', 'REPUESTOS', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (2, 'ELECTRICOS', 'ELECTRICOS', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (3, 'SUMI__PLAN', 'SUMI. PLANTA', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (4, 'SUMI____OT', 'SUMI. - OTROS', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (5, 'HERRAMIENT', 'HERRAMIENTAS', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (6, 'SUMI__MATR', 'SUMI. MATRICERIA', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (7, 'OTROS', 'OTROS', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (8, 'ACCESORIOS', 'ACCESORIOS', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (9, 'MAT__AUX__', 'MAT. AUX. ACCESORIOS', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (10, 'CONEXIONES', 'CONEXIONES', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (11, 'COMPLEMENT', 'COMPLEMENTOS VARIOS', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (12, 'ABRASIVOS', 'ABRASIVOS', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (13, 'UNIFORMES', 'UNIFORMES', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (14, 'MATERIALES', 'MATERIALES', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (15, 'SUMI____EN', 'SUMI. - ENERGIA', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (16, 'PERNERIA', 'PERNERIA', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (17, 'MERCADERIA', 'MERCADERIA.MANUF.', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (18, 'GENERAL', 'GENERAL', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (19, 'SOLDARURA', 'SOLDARURA', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (20, 'EMBALAJES', 'EMBALAJES', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (21, 'EPP', 'EPP', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (22, 'FIERRRO___', 'FIERRRO / VARILLA', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (23, 'CORREDIZO', 'CORREDIZO', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (24, 'POST_VENTA', 'POST-VENTA', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (25, 'UTILES', 'UTILES', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (26, 'LIMPIEZA_Y', 'LIMPIEZA Y SEG.', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (27, 'LUBRICANTE', 'LUBRICANTES', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (28, 'PINTURA', 'PINTURA', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (29, 'UTILES_DE_', 'UTILES DE OFICINA Y COMPUTO', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (30, 'MANIFOLD_G', 'MANIFOLD GAS NATURAL', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (31, 'COMBUSTIBL', 'COMBUSTIBLES', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (32, 'SOLVENTES', 'SOLVENTES', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (33, 'PERFIL', 'PERFIL', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (34, 'COBERT_Y_C', 'COBERT Y CERRAMIENTO', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (35, 'RACK', 'RACK', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (36, 'PROD__TERM', 'PROD. TERM NO ESTAND', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (37, 'RIEL___CAN', 'RIEL / CANAL', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (38, 'TUBOS', 'TUBOS', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (39, 'BOBINAS_DE', 'BOBINAS DE ACERO', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (40, 'REPUESTOS_', 'REPUESTOS 13', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (41, 'ACTIVOS', 'ACTIVOS', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (42, 'PROD_TERM_', 'PROD TERM ACCESORIOS', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (43, '_N_D', '#N/D', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (44, 'H_MEDICINA', 'H.MEDICINAL', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (45, 'LIMPIEZA', 'LIMPIEZA', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (46, 'LINEA_DE_E', 'LINEA DE ENERGIA', '') ON CONFLICT DO NOTHING;
INSERT INTO grupos_articulos (id, codigo, nombre, descripcion) VALUES (47, 'QUIMICOS', 'QUIMICOS', '') ON CONFLICT DO NOTHING;
SELECT setval('grupos_articulos_id_seq', (SELECT MAX(id) FROM grupos_articulos));

