import type { ConteoForm } from "./types";

export const FAMILIA2_OPTIONS = [
  "REPUESTO",
  "CONSUMIBLE",
  "HERRAMIENTAS",
  "EPP",
  "MATERIALES",
  "ACCESORIO",
  "ECONOMATO",
  "SUMINISTRO",
  "PINTURA",
  "LIMPIEZA",
  "OTRO",
];

export const PRESENTACION_OPTIONS = [
  "CAJA",
  "SUELTO",
  "EMPAQUE",
  "EMBASE",
  "BOLSA",
  "ROLLO",
  "ENVUELTO",
  "SPRAY",
  "PAQUETE",
  "BIDON",
  "RODILLO",
  "SACO",
  "BALDE",
  "BALDE DE LATA",
  "OTRO",
];

export const UM_OPTIONS = [
  "UND",
  "CIEN",
  "PAR",
  "MT",
  "JGO",
  "KG",
  "GL",
  "MTS",
  "MIL",
  "CJA",
  "LT",
  "PAQ",
  "RLLO",
  "GALON",
];

export const getDefaultForm = (): ConteoForm => ({
  producto: "",
  lote: "",
  descripcion: "",
  stock_sistema: 0,
  unidad: "UND",
  familia: "",
  familia2: "REPUESTO",
  cantidad_fisica: 0,
  um: "UND",
  presentacion: "SUELTO",
  n_cajas_bultos: "1 UND",
  largo: 0,
  ancho: 0,
  alto: 0,
  peso_aprox_unitario: 0,
  observacion: "OK",
  comentario: "",
  rack: "",
  ubicacion_actual: "",
  almacenamiento: "",
  contenedor: "",
});
